### PR TITLE
Replace PNG assets with lossless optimized variants

### PR DESCRIPTION
**Pull request by riverar**
Replaces loose PNG assets with optimized variants sans embedded text/metadata sections and recompressed streams (Zopfli). This process does not affect image quality in any way.

Some of the larger assets were located in project template paths that impacted all users (e.g. dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/WinUI.Desktop.Cs.ClassLibrary.png was 89KB too large).

Saved bytes: 965,968 (~943KB)

ICO assets with embedded PNGs were left untouched and will be addressed in a separate PR.

### CODE REVIEW

**Review by Scottj1s — APPROVED** [review]
thanks @riverar!  curious - what tool did you use?

**Comment by riverar** [comment]
@Scottj1s Scripted pngdistill (part of Fiddler) for now 👍

**Review by DrusTheAxe — APPROVED** [review]
Very nice!

**Comment by Scottj1s** [comment]
@BenJKuhn , @kythant - some failing builds which shouldn't hold up merge of this PR

**Comment by Scottj1s** [comment]
Note: PNG/ICO compression removes about 1MB from the 75MB VSIX, so not essential for 0.5 Preview.

**Comment by riverar** [comment]
The cost of data differs around the world; data plans in the United States [are on the expensive side](https://www.forbes.com/sites/niallmccarthy/2019/03/05/the-cost-of-mobile-internet-around-the-world-infographic/?sh=87ee9c8226e5) of the spectrum. Some folks stuck with [satellites for broadband access pay $15/MB](https://spacenews.com/satellite-broadband-firm-charges-megabyte/)! We really should treat size reductions with a much higher appreciation and priority, to ensure Project Reunion appeals to (and can be downloaded by) the widest possible audience.

That said, I understand this came in late for 0.5. 😆

**Pull request merged**
