### PR TITLE
Update MRTCore to .net 5.0.3

### PR DESCRIPTION
**Pull request by huichen123**
This is required for using CSWinRT 1.2

### CODE REVIEW

**Comment by huichen123** [comment]
add a comment

**Comment by huichen123** [comment]
@BenJKuhn , I added a comment, and the build still doesn't run.

**Comment by riverar** [comment]
Something to consider replacing the manual .NET runtime installation scripts here https://github.com/actions/setup-dotnet

**Review by axelandrejs — APPROVED** [review]

**Comment by huichen123** [comment]
> Perhaps in the future, consider replacing the manual .NET runtime installation scripts with the setup-dotnet GitHub Action https://github.com/actions/setup-dotnet
> 
> ```
> - uses: actions/setup-dotnet@v1
>   with:
>     dotnet-version: '5.0.x'
> ```

This is not built with github action, but Azure DevOp. There is built-in task to install .net in ADO, but my impression is that doesn't install latest versions.

**Pull request merged**
