### PR TITLE
Add PushNotifications folder to the project

### PR DESCRIPTION
**Pull request by sharath2727**
Description: Creating a PushNotifications Project for handling push notifications.

### CODE REVIEW

**Comment by jonwis** [comment]
We've been putting code under `dev/componentname` using shared VCProj files, which link into the overall Project Reunion DLL.  Check out #416 for an example.

@EHO-makai , can you conjure up some "how to add a sub project" documentation? My "samples" sample was removed at some point. :)

**Comment by jevansaks** [comment]
We've done this enough in WinUI2 that folks on our team finally wrote a script to add new controls. It creates the directory, the projitems, updates the .sln and all that obnoxious stuff people always forget to do. You can find (and hopefully steal heavily from) that script here: https://github.com/microsoft/microsoft-ui-xaml/blob/master/tools/GenerateNewControlProject.ps1

**Comment by sharath2727** [comment]
Hi Jon, I think I made a very naive mistake. I have a habit of using git add -u which basically did not add the .vcxitems shared project. Fixed it now. However, I will still check the link https://github.com/microsoft/microsoft-ui-xaml/blob/master/tools/GenerateNewControlProject.ps1. Thanks.

**Comment by jonwis** [comment]
Oh man I've done that too.  No worries, looking forward to seeing this come in!

**Review by danielayala94 — APPROVED** [review]

**Pull request merged**
