### PR TITLE
Copy Microsoft.ProjectReunion.Bootstrap.dll to $(OutDir) for non-native projects.

### PR DESCRIPTION
**Pull request by rohanp-msft**
This file was not being bin placed but needs to be.

**How verified**
Used a test app.

### CODE REVIEW

**Comment by huichen123** [comment]
also need a build pipeline change.

**Comment by rohanp-msft** [comment]
> also need a build pipeline change.

can you elaborate, please?

**Comment by huichen123** [comment]
the new file needs to get into the package.

---
In reply to: [847219658](https://github.com/microsoft/ProjectReunion/pull/855#issuecomment-847219658) [](http://example.com/codeflow?ancestors=847219658,847219658)

**Review by axelandrejs — APPROVED** [review]

**Comment by huichen123** [comment]
>         Copy-Item -Path "$targetsFilePath\ProjectReunion-Nuget-Native.targets" -Destination "$fullpackagePath\build\native\Microsoft.ProjectReunion.Foundation.targets"

also needs to be in this file

---
Refers to: build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml:53 in 550b47b. [](commit_id = 550b47b31f1ace37078aefdd213a0bee3cf86355, deletion_comment = False)

**Comment by rohanp-msft** [comment]
> build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml

We don't want this import for native. It applies to non-native only.

**Comment by huichen123** [comment]
no unpackaged support for native app?

---
In reply to: [847274120](https://github.com/microsoft/ProjectReunion/pull/855#issuecomment-847274120) [](http://example.com/codeflow?ancestors=847274120,847274120)

**Comment by huichen123** [comment]
> > build/AzurePipelinesTemplates/ProjectReunion-CreateNugetPackage-Job.yml
> 
> We don't want this import for native. It applies to non-native only.

@DrusTheAxe , does this only apply to non-native?

**Review by huichen123 — APPROVED** [review]

**Pull request merged**
